#include "cmake_deps.h"

#include <filesystem>
#include <fstream>
#include <print>

namespace forge::commands {

void write_cmake_deps(const ForgeToml& manifest) {
    std::filesystem::create_directories(".forge");

    std::ofstream out(".forge/deps.cmake");
    if (!out.is_open()) {
        std::println(stderr, "failed to write .forge/deps.cmake");
        std::exit(1);
    }

    out << "# AUTO-GENERATED by forge — do not edit by hand.\n"
        << "# Regenerated on every `forge add`/`forge remove`. Any manual\n"
        << "# changes here will be overwritten.\n\n"
        << "include(FetchContent)\n\n";

    for (const Package& pkg : manifest.packages) {
        out << "FetchContent_Declare(\n"
            << "    " << pkg.package_name << "\n"
            << "    GIT_REPOSITORY " << pkg.source.url << "\n"
            << "    GIT_TAG        " << pkg.source.commit_hash << "\n"
            << ")\n";
    }

    if (!manifest.packages.empty()) {
        out << "\nFetchContent_MakeAvailable(\n";
        for (const Package& pkg : manifest.packages) {
            out << "    " << pkg.package_name << "\n";
        }
        out << ")\n";
    }
}

} // namespace forge::commands
